apiVersion: v1 
kind: Service 
metadata: 
  name: helloworld-java-service 
spec: 
  selector: 
    app: helloworld-java 
  ports: 
    - protocol: TCP 
      port: 80 
      targetPort: 8080 
  type: LoadBalancer 

# to apply:
# kubectl apply -f service.yaml